### ISSUE TITLE
There is currently a build issue using mdtool whilst using Xamarin.Insights component.

### ISSUE THREAD

**Issue by Letibee** [bitrise-steplib/steps-xamarin-builder#18]
Xamarin seems to be neglecting the mdtool build path in favour of xbuild. It might be worth moving over to xbuild for better future proofing and support.

This is visible in any Xamarin project using insights with the Xamarin builder 1.0.0 (maybe prior) -> 1.0.5

**Comment by birmacher** [comment]
Hey @Letibee!

We moved to mdtool, because there are a couple features that xbuild will skip, like the `custom commands` or the `referenced projects`.

Currently there is a known-issue with Xamarin.Insights.
Bugreport: https://bugzilla.xamarin.com/show_bug.cgi?id=36421
Solution: http://forums.xamarin.com/discussion/comment/168445/#Comment_168445

In short you should simply remove the < XamarinInsightsApiKey> param from your csproj and add the key manually to your source code.
This will be fixed in the next release ( https://bugzilla.xamarin.com/show_bug.cgi?id=36421#c5 )

Please note that this won't break anything with Xamarin.Insights.

Let me know if it solved your issue or if you need any help with it!

**Comment by Letibee** [comment]
Indeed! I've since removed the XamarinInsightsApiKey and fixed issue. :)
