### ISSUE TITLE
Android project is compiled with iPhone configuration

### ISSUE THREAD

**Issue by lakario** [bitrise-steplib/steps-xamarin-builder#8]
Our solution contains both iOS and Android clients. The xamarin-builder step is building and archiving the Android project when the configuration is set to iPhone. It should be possible to disable this extraneous step.

**Comment by birmacher** [comment]
When building the solution we will build all the included csprojs. In most cases there is a mapping from the configuration & platform defined in the solution to the configs & platform for the project.
For Android projects most of the time it's iPhone -> AnyCPU.

If you only want to build the Android or iOS project you can simply just add the required csproj instead of the solution.

Let me know if it helps or if you need any more information!

**Comment by lakario** [comment]
The solution's build configuration is one that excludes the Android project from compilation for the config we are using for iPhone. If I build this solution from VS or Xamarin Studio, it will skip Android, as expected. Am I missing something here with regards to BitRise?

Adding just the iOS project or just the Android project to BitRise, rather than the solution, presents other issues as we have project dependencies in the solution which need to be compiled at the same time as the clients.

**Comment by birmacher** [comment]
Hey @lakario!

It should be resolved from 1.0.2. If you hit the same problem again please reopen the ticket.
